apiVersion: apps/v1
kind: Deployment
metadata:
  name: pribox-analytics-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pribox-analytics-service
  template:
    metadata:
      labels:
        name: pribox-analytics-service
    spec:
      containers:
      - image: pribox.azurecr.io/pribox-analytics-service
        imagePullPolicy: Always
        name: pribox-analytics-service
        envFrom:
        - secretRef:
            name: "config-pribox-analytics-service"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: pribox-analytics-service
  name: pribox-analytics-service
  namespace: default
  labels:
    name: pribox-analytics-service
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 5003
    targetPort: 5003
  selector:
    name: pribox-analytics-service
---