apiVersion: apps/v1
kind: Deployment
metadata:
  name: pribox-analytics-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pribox-analytics-service
  template:
    metadata:
      labels:
        name: pribox-analytics-service
    spec:
      containers:
        - image: pribox.azurecr.io/pribox-analytics-service-staging
          imagePullPolicy: Always
          name: pribox-analytics-service
          envFrom:
            - secretRef:
                name: 'config-pribox-analytics-service'

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: pribox-analytics-service-staging
  name: pribox-analytics-service
  namespace: staging
  labels:
    name: pribox-analytics-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5003
      targetPort: 5003
  selector:
    name: pribox-analytics-service
---
